apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rag-app
  template:
    metadata:
      labels:
        app: rag-app
    spec:
      containers:
      - name: rag-app-container
        image: rag-app:latest
        ports:
        - containerPort: 8000